executable			= run_updated2_tuning_step3.sh
#arguments			= $(arg1)
arguments			= 1

+JobFlavour		= "testmatch"

output					= my_updated2_tuning_step3.$(ClusterId).$(ProcId).out
error						= my_updated2_tuning_step3.$(ClusterId).$(ProcId).err
log							= my_updated2_tuning_step3.$(ClusterId).log

should_transfer_files = YES
transfer_input_files = singlebeam_updated2_tuning_step3.tcl
transfer_output_files = ""

#queue arg1 from input3.txt
queue
