executable			= run_updated2_tuning_step2.sh
arguments			= $(arg1)
#arguments			= 94

+JobFlavour		= "testmatch"

output					= my_updated2_tuning_step2.$(ClusterId).$(ProcId).out
error						= my_updated2_tuning_step2.$(ClusterId).$(ProcId).err
log							= my_updated2_tuning_step2.$(ClusterId).log

should_transfer_files = IF_NEEDED
transfer_output_files = ""

queue arg1 from input_perfect.txt
#queue arg1 from input2.txt
#queue


