executable  = run_singlebeam_tuning_step1.sh
arguments   = $(arg1)

+JobFlavour	= "testmatch"

output      = log_singlebeam_tuning_step1.$(ClusterId).$(ProcId).out
error       = log_singlebeam_tuning_step1.$(ClusterId).$(ProcId).err
log         = log_singlebeam_tuning_step1.$(ClusterId).log

should_transfer_files   = YES
transfer_input_files    = singlebeam_tuning_step1.tcl
transfer_output_files   = ""

queue arg1 from input.txt
